### ISSUE TITLE
robinhood broker backend

### ISSUE THREAD

**Issue by tgoodlet** [pikers/piker#2]
Huh, turns out someone has [reverse engineered and built a client for](https://github.com/aurbano/Robinhood-Node) the robinhood api. 

I'd like to do the same with using `trio` and for starters see if we can use their quote system for cross-referencing data feeds. It'd also be interesting to toy with creating a routing system that issues orders to the cheapest broker per market/symbol.

**Comment by tgoodlet** [comment]
Shoot just when I was getting all excited about this I find out you have to be n'merican [to open an account...](https://support.robinhood.com/hc/en-us/articles/202844889-Account-Opening-Requirements). 

Lame.

Guess I'll have to wait for some yankee cronies to join me.

**Comment by dkeitel** [comment]
Like me?

**Comment by tgoodlet** [comment]
@dkeitel woot! 
 
I'd actually be happy to do the work if you can to get me access to an unfunded account.
Really I'm just looking to get (real-time) quotes working for now.

**Comment by dkeitel** [comment]
Haha yea I was going to say I don’t think I want to risk my account by using the reverse engineered API :).

Off-topic but E*TRADE has an API that I have a token for that might fit the bill as well?

**Comment by tgoodlet** [comment]
Yeah it'd be nice to get full support for `robinhood` but obviously it'll take some tinkering.

I'm open to supporting whatever brokerages are desired. E*trade looks just fine.
Right now things are nowhere near the point where a standard backend API has formed but that will be one of the things to consider and document as brokers are added.

**Comment by dkeitel** [comment]
```curl https://api.robinhood.com/quotes/QCOM/``` actually seems to work without any keys/auth.

**Comment by tgoodlet** [comment]
waaaat that's lit!

**Comment by dkeitel** [comment]
> Seems only US exchange stuff though?

I think that's all you can trade on Robinhood right now anyways?

**Comment by tgoodlet** [comment]
Yeah more so I was looking for minor exchange / OTC stuff but I guess that [isn't supported yet](https://support.robinhood.com/hc/en-us/articles/208650286-Stocks-Available-on-Robinhood).

Good to know.
This at least makes it easy enough to write another quote streaming backend for the moment.

**Comment by tgoodlet** [comment]
@dkeitel I actually would like to get quoting in sooner then later for testing because I'm starting to get people playing this that don't have broker accounts - so the free quotes from RB fits well.

I was going to take a stab at it unless you feel so inclined. 
Might be some good fun to learn some [`trio`](https://github.com/python-trio/trio)!

**Comment by dkeitel** [comment]
I may not be able to get to it as soon as you would hope, but I’d gladly do a code review / verification to learn about trio :)
