### ISSUE TITLE
Add Support for Open Orders

### ISSUE THREAD

**Issue by iamzoltan** [pikers/piker#293]
It would be nice if we could add a message schema to deal with open orders stored with your broker, so that we could grab them and display them on piker.

In addition, I would like to add the possibility to save and reload dark orders and potentially paper engine orders as well.

**Comment by iamzoltan** [comment]
@goodboy I think ill take a crack at this guy next, since I use kraken to hold open orders. It would be nice to be able to save dark orders too, something I can tackle next.

**Comment by iamzoltan** [comment]
man, I am a stale ol' bish, well get on this asap

**Comment by goodboy** [comment]
@iamzoltan we're basically primed for it after #349 lands if interested 😉

**Comment by goodboy** [comment]
Prettty sure this was completely solved in https://github.com/pikers/piker/pull/374.

**Comment by goodboy** [comment]
Follow up in https://github.com/pikers/piker/issues/384
