### ISSUE TITLE
`kraken`: order mode modifcation of orders doesn't cancel/edit the order and instead just leaves them stale! 

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#299]
Massive bug that i'm not sure how we missed...

Currently there's no use of the [`editOrder`](https://docs.kraken.com/rest/#operation/editOrder) endpoint and further no cancelling of submitted live orders such that if a user modified a live submission the original order **is left stale** without any indication of this to the user and further a new order is submitted at the new target price..

This is a massive issue and needs to be addressed asap!

I will be disabling kraken order mode support in #298 until this is resolved.

**Comment by iamzoltan** [comment]
addressed in a new PR #300

**Comment by iamzoltan** [comment]
PR #300 merged
