### ISSUE TITLE
Pps toml header leaking after zeroing positions

### ISSUE THREAD

**Issue by jaredgoldman** [pikers/piker#472]
When a user enters a position, stops the service tree and then boots it back up and zeroes the pp, the header for the position i.e `[binance.paper]` is leaked. It might have to do with the way we're loading the pps when booting up the paper actor to update UI slotting but by default we shouldn't be writing on that call. The expected behavior is that once a position is cleared, no record will appear in a user's `pps.toml`. 

For context, these issues were reported in https://github.com/pikers/piker/pull/462
- https://github.com/pikers/piker/pull/462#issuecomment-1448654512
- https://github.com/pikers/piker/pull/462#issuecomment-1438852266

**Comment by goodboy** [comment]
Pretty sure this was mostly resolved prior to #489 but either way it's solved by that for sure since we're no longer doing mult-broker pps files and instead each broker account has it's own `account...toml` file now B)
