### ISSUE TITLE
QT apps

### ISSUE THREAD

**Issue by goodboy** [pikers/piker#52]
The rumour is `kivy` is much better for mobile and `QT` for desktop.
I want to eventually have some pretty serious desktop tools with responsiveness similar to a technical editor or DAW.

Resources worth sniffing out:
- `asyncio` integration with `QT` using [quamash](https://github.com/harvimt/quamash) for which there's discussion surrounding similar `trio` support in python-trio/trio#399
- the *QT for Python* [getting started](https://doc-snapshots.qt.io/qtforpython/gettingstarted.html) and extensive [module index](https://doc-snapshots.qt.io/qtforpython/index.html)

I've also been thinking about bypassing the `quamash`-integrated-with-`trio` approach using `tractor` and simply adding an adapter that speaks the portal protocol to get the needed integration.

**Comment by tgoodlet** [comment]
Nice little example in the [ib_insync docs](https://rawgit.com/erdewit/ib_insync/master/docs/html/recipes.html).

**Comment by goodboy** [comment]
Woot!

[triqt](https://github.com/henry232323/triqt) seems to have tackled `trio` in the Qt event loop :smirk:

**Comment by goodboy** [comment]
Lol, yeah i guess this has been solved for a long long while now with our integration with `Qt` via `trio`'s guest mode 😂
