### ISSUE TITLE
Experiment with pyqtgraph for charting

### ISSUE THREAD

**Issue by iamzoltan** [pikers/piker#80]
As per #10, work on getting pyqtgraph's example customGraphicsItem.py working with the native candle sticks object in qt.

**Comment by goodboy** [comment]
Turns out `pyside2` [is broken on python 3.8](https://bugs.archlinux.org/task/64514)...
Apparently `5.14` should fix it - have yet to try it.

**Comment by goodboy** [comment]
Yup `5.14` of `pyside2` did indeed fix it.

**Comment by goodboy** [comment]
Looks like peeps have [had problems with real-time charting many graphs](https://forum.qt.io/topic/76744/multiple-real-time-plots-charts/2) using std Qt stuff. I wonder if `pyqtgraph` solves and problems like this? If not we could consider just always running subgraphs in separate `tractor` actors?

**Comment by goodboy** [comment]
Some immediately Relevant examples from pyqtgraph project I've tried.

These files are found under the [examples/ dir in the root repo](https://github.com/pyqtgraph/pyqtgraph/tree/develop/examples) folder:
- `customGraphicsItem.py`: example of candlestick plot
- `scrollingPlots.py`: realtime data feed scrolling
- `crosshair.py`: example crosshair cursor
- `ViewBoxFeatures.py`: example of auto-fitting y-data to axes
- `PanningPlot.py`: auto-scale realtime feed y-axis
- `historgram.py`: self explanatory
- `customPlot.py`: show's how to make right-click reset view and dates on x-axi

**Comment by goodboy** [comment]
Lol, i guess we can safely say we decided that `pyqtgraph` was a decent choice 😂 😹 🕹️
