### ISSUE TITLE
QtChart

### ISSUE THREAD

**Issue by gxjcc** [pikers/piker#81]
When I use QtChart, It reminds me that the qtchart_qchartview.h do not exist. Who can tell me why!

**Comment by goodboy** [comment]
Hey @gxjcc. 

Heh, that's a good question. I haven't had that problem with `PySide2`. You might want to check your `Qt` installation and/or hop into the [pyside gitter channel](https://gitter.im/PySide/pyside2) to ask for help. 

This project isn't for `Qt` support (yet).
